### ISSUE TITLE
Training 2D heatmap

### ISSUE THREAD

**Issue by steakerlife** [hwangdonghyun/VNect-TensorFlow-Keras#2]
Hi there - I am trying to train the 2d heatmap using data that I generated myself using the kinect for windows sdk. I am also using images that are 540x540px and created 2d heatmaps (68x68px) from that data, but I am not seeing results that would lead me to believe that I am on the right path. Can you further elaborate on what you changed about the model's structure when training the 2d heatmap (in addition to what you've referenced in your bullet points)?

**Comment by hwangdonghyun** [comment]
In my case, I just made a very simple structure to estimate 2D heatmaps after ResNet stage4.
I trained this network and then copy ResNet's weight to the current model and train it with LRMult.
I think that a large input size makes more computation, but it seems to be okay for me if you don't care about that.
